import type { ThemeConfig } from 'antd'

const sharedTokens = {
  fontFamily: `-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif`,
  fontFamilyCode: `'SF Mono', SFMono-Regular, ui-monospace, Menlo, Consolas, Liberation Mono, monospace`,
  fontSize: 13,
  fontSizeSM: 12,
  fontSizeLG: 14,
  fontSizeHeading3: 20,
  fontSizeHeading4: 17,
  fontSizeHeading5: 14,
  fontWeightStrong: 600,
  borderRadius: 8,
  borderRadiusSM: 6,
  borderRadiusLG: 12,
  controlHeight: 34,
  controlHeightSM: 30,
  padding: 24,
  paddingSM: 16,
  paddingXS: 12,
  paddingXXS: 8,
  margin: 24,
  marginSM: 16,
  marginXS: 8,
  marginXXS: 4,
}

export const lightTheme: ThemeConfig = {
  token: {
    ...sharedTokens,
    colorPrimary: '#2563eb',
    colorBgLayout: '#f1f5f9',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    colorBgSpotlight: '#f8fafc',
    colorBorder: '#e2e8f0',
    colorBorderSecondary: '#eef1f6',
    colorText: '#0f172a',
    colorTextSecondary: '#475569',
    colorTextTertiary: '#94a3b8',
    colorTextQuaternary: '#cbd5e1',
    colorSuccess: '#16a34a',
    colorWarning: '#d97706',
    colorError: '#dc2626',
    colorInfo: '#2563eb',
    colorLink: '#2563eb',
    colorLinkHover: '#1d4ed8',
  },
  components: {
    Layout: {
      headerBg: '#ffffff',
      headerHeight: 52,
      headerPadding: '0 24px',
      siderBg: '#ffffff',
      bodyBg: '#f1f5f9',
    },
    Card: {
      paddingLG: 20,
      borderRadiusLG: 12,
    },
    Table: {
      headerBg: '#f8fafc',
      headerColor: '#64748b',
      fontSize: 13,
      rowHoverBg: '#f8fafc',
      borderColor: '#eef1f6',
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
      cellPaddingBlockSM: 10,
      cellPaddingInlineSM: 12,
    },
    Button: {
      borderRadius: 8,
      borderRadiusSM: 6,
      borderRadiusLG: 10,
      controlHeight: 34,
      controlHeightSM: 30,
      controlHeightLG: 40,
      fontWeight: 500,
      paddingInline: 16,
      paddingInlineSM: 12,
    },
    Input: {
      borderRadius: 8,
      controlHeight: 34,
      controlHeightSM: 30,
    },
    InputNumber: {
      borderRadius: 8,
      controlHeight: 34,
    },
    Select: {
      borderRadius: 8,
      controlHeight: 34,
    },
    Modal: {
      borderRadiusLG: 16,
      paddingContentHorizontalLG: 24,
    },
    Dropdown: {
      borderRadiusLG: 12,
      paddingBlock: 4,
    },
    Popover: {
      borderRadiusLG: 12,
    },
    Tooltip: {
      borderRadiusLG: 8,
    },
    Tag: {
      borderRadiusSM: 6,
      defaultBg: '#f1f5f9',
      defaultColor: '#475569',
    },
    Statistic: {
      contentFontSize: 22,
      titleFontSize: 12,
    },
    Menu: {
      borderRadius: 8,
      itemBorderRadius: 8,
      itemMarginInline: 4,
      itemPaddingInline: 12,
    },
    Tabs: {
      borderRadius: 8,
      cardHeight: 36,
    },
    Skeleton: {
      colorFill: '#f1f5f9',
      colorFillContent: '#e8ecf1',
      borderRadius: 8,
    },
  },
}

export const darkTheme: ThemeConfig = {
  token: {
    ...sharedTokens,
    colorPrimary: '#3b82f6',
    colorBgLayout: '#0a0a0a',
    colorBgContainer: '#141414',
    colorBgElevated: '#1a1a1a',
    colorBgSpotlight: '#1e1e1e',
    colorBorder: '#262626',
    colorBorderSecondary: '#1f1f1f',
    colorText: '#e5e7eb',
    colorTextSecondary: '#9ca3af',
    colorTextTertiary: '#6b7280',
    colorTextQuaternary: '#4b5563',
    colorSuccess: '#22c55e',
    colorWarning: '#f59e0b',
    colorError: '#ef4444',
    colorInfo: '#3b82f6',
    colorLink: '#3b82f6',
    colorLinkHover: '#60a5fa',
  },
  components: {
    Layout: {
      headerBg: '#111111',
      headerHeight: 52,
      headerPadding: '0 24px',
      siderBg: '#111111',
      bodyBg: '#0a0a0a',
    },
    Card: {
      paddingLG: 20,
      borderRadiusLG: 12,
    },
    Table: {
      headerBg: '#111111',
      headerColor: '#9ca3af',
      fontSize: 13,
      rowHoverBg: '#1a1a1a',
      borderColor: '#1f1f1f',
      cellPaddingBlock: 14,
      cellPaddingInline: 16,
      cellPaddingBlockSM: 10,
      cellPaddingInlineSM: 12,
    },
    Button: {
      borderRadius: 8,
      borderRadiusSM: 6,
      borderRadiusLG: 10,
      controlHeight: 34,
      controlHeightSM: 30,
      controlHeightLG: 40,
      fontWeight: 500,
      paddingInline: 16,
      paddingInlineSM: 12,
    },
    Input: {
      borderRadius: 8,
      controlHeight: 34,
      controlHeightSM: 30,
    },
    InputNumber: {
      borderRadius: 8,
      controlHeight: 34,
    },
    Select: {
      borderRadius: 8,
      controlHeight: 34,
    },
    Modal: {
      borderRadiusLG: 16,
      paddingContentHorizontalLG: 24,
    },
    Dropdown: {
      borderRadiusLG: 12,
      paddingBlock: 4,
    },
    Popover: {
      borderRadiusLG: 12,
    },
    Tooltip: {
      borderRadiusLG: 8,
    },
    Tag: {
      borderRadiusSM: 6,
      defaultBg: '#1f1f1f',
      defaultColor: '#9ca3af',
    },
    Statistic: {
      contentFontSize: 22,
      titleFontSize: 12,
    },
    Menu: {
      borderRadius: 8,
      itemBorderRadius: 8,
      itemMarginInline: 4,
      itemPaddingInline: 12,
    },
    Tabs: {
      borderRadius: 8,
      cardHeight: 36,
    },
    Skeleton: {
      colorFill: '#1a1a1a',
      colorFillContent: '#222222',
      borderRadius: 8,
    },
  },
}
